#!/usr/bin/env python3
"""Generate both implementation lanes from `catalog/`.

Deterministic and idempotent: same catalog in, byte-identical files out,
regardless of platform, hash seed, or how many times it is run. That is
what lets `validate.py` regenerate into a temp directory and diff against
what is checked in.

Usage:
    python3 scripts/generate.py                 # write into the repository
    python3 scripts/generate.py --out DIR       # write into DIR instead
    python3 scripts/generate.py --check         # exit 1 if anything is stale

Outputs (relative to the output root):
    implementations/swift/Resources/<locale>.lproj/Localizable.strings
    implementations/swift/Resources/<locale>.lproj/Localizable.stringsdict
    implementations/swift/Sources/VibeBarLocalization/Generated/L10n.swift
    implementations/typescript/src/generated/catalog.ts
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from typing import Dict, List, Optional, Sequence, Tuple

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from _catalog import (  # noqa: E402
    ARG,
    HASH,
    PLURAL,
    PLURAL_CATEGORIES,
    SOURCE_LOCALE,
    SWIFT_TYPE,
    TEXT,
    TS_TYPE,
    Catalog,
    CatalogError,
    Entry,
    FORMAT_SPECIFIER,
    Node,
    load_all,
    parse_icu,
    plural_arguments,
    rel,
    specifier,
)

BANNER_LINE = "Generated by scripts/generate.py from catalog/. Do not edit."
BANNER_HINT = "Edit catalog/*.json and re-run `python3 scripts/generate.py`."


def ts_string(text: str) -> str:
    """A TypeScript string literal. Non-ASCII stays readable, not \\uXXXX."""
    return json.dumps(text, ensure_ascii=False)


SWIFT_KEYWORDS = {
    "Any", "as", "associatedtype", "associativity", "break", "case", "catch",
    "class", "continue", "convenience", "default", "defer", "deinit", "didSet",
    "do", "dynamic", "else", "enum", "extension", "fallthrough", "false",
    "fileprivate", "final", "for", "func", "get", "guard", "if", "import", "in",
    "indirect", "infix", "init", "inout", "internal", "is", "lazy", "left",
    "let", "mutating", "nil", "none", "nonmutating", "open", "operator",
    "optional", "override", "postfix", "precedence", "prefix", "private",
    "protocol", "public", "repeat", "required", "rethrows", "return", "right",
    "self", "Self", "set", "static", "struct", "subscript", "super", "switch",
    "throw", "throws", "true", "try", "typealias", "unowned", "var", "weak",
    "where", "while", "willSet",
}


# --------------------------------------------------------------------------
# Small helpers
# --------------------------------------------------------------------------


def swift_identifier(segment: str) -> str:
    return "`%s`" % segment if segment in SWIFT_KEYWORDS else segment


def swift_namespace(segment: str) -> str:
    name = segment[:1].upper() + segment[1:]
    return "`%s`" % name if name in SWIFT_KEYWORDS else name


def swift_literal(text: str) -> str:
    out = text.replace("\\", "\\\\").replace('"', '\\"')
    out = out.replace("\n", "\\n").replace("\t", "\\t").replace("\r", "\\r")
    return '"%s"' % out


def strings_literal(text: str) -> str:
    """A quoted, escaped token for a `.strings` file."""
    out = text.replace("\\", "\\\\").replace('"', '\\"')
    out = out.replace("\n", "\\n").replace("\t", "\\t").replace("\r", "\\r")
    return '"%s"' % out


def xml_text(text: str) -> str:
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def doc_comment(text: str, indent: str) -> List[str]:
    return ["%s/// %s" % (indent, line) for line in text.split("\n")]


def uses_positional(entry: Entry) -> bool:
    """More than one value means the translation may reorder them."""
    return len(entry.placeholders) > 1


# --------------------------------------------------------------------------
# Rendering an ICU message into Apple format strings
# --------------------------------------------------------------------------


def render_flat(nodes: Sequence[Node], entry: Entry, plural_name: Optional[str] = None) -> str:
    """Message with every argument replaced by its C format specifier.

    `plural_name`, when given, is the plural argument whose `#` tokens are
    being rendered — used for the inside of a `.stringsdict` branch.
    """
    parts: List[str] = []
    positional = uses_positional(entry)
    for node in nodes:
        if node[0] == TEXT:
            parts.append(node[1].replace("%", "%%"))
        elif node[0] == ARG:
            parts.append(specifier(entry, node[1], positional))
        elif node[0] == HASH:
            if plural_name is None:
                raise CatalogError("%s: `#` outside a plural branch" % entry.key)
            parts.append(specifier(entry, plural_name, positional))
        elif node[0] == PLURAL:
            raise CatalogError(
                "%s: nested plurals are not supported by the .stringsdict writer" % entry.key
            )
    return "".join(parts)


def render_format_key(nodes: Sequence[Node], entry: Entry) -> str:
    """`NSStringLocalizedFormatKey`: plurals become `%#@name@` variables."""
    parts: List[str] = []
    positional = uses_positional(entry)
    for node in nodes:
        if node[0] == TEXT:
            parts.append(node[1].replace("%", "%%"))
        elif node[0] == ARG:
            parts.append(specifier(entry, node[1], positional))
        elif node[0] == PLURAL:
            name = node[1]
            if positional:
                index = entry.placeholder_order.index(name) + 1
                parts.append("%%%d$#@%s@" % (index, name))
            else:
                parts.append("%%#@%s@" % name)
        elif node[0] == HASH:
            raise CatalogError("%s: `#` outside a plural branch" % entry.key)
    return "".join(parts)


def selector_sort_key(selector: str) -> Tuple[int, int, str]:
    if selector.startswith("="):
        return (0, int(selector[1:]), selector)
    return (1, PLURAL_CATEGORIES.index(selector), selector)


# --------------------------------------------------------------------------
# Swift lane: Localizable.strings
# --------------------------------------------------------------------------


def emit_strings(source: Catalog, catalog: Catalog, plural_keys: Sequence[str]) -> str:
    lines = [
        "/* %s" % BANNER_LINE,
        "   %s" % BANNER_HINT,
        "   Locale: %s" % catalog.locale,
        "   Plural keys live in Localizable.stringsdict, not here. */",
        "",
    ]
    plural_set = set(plural_keys)
    for key in sorted(catalog.entries):
        if key in plural_set:
            continue
        source_entry = source.entries[key]
        entry = Entry(
            key=key,
            value=catalog.entries[key].value,
            comment=source_entry.comment,
            placeholders=source_entry.placeholders,
        )
        comment = source_entry.comment or ""
        lines.append("/* %s */" % comment.replace("*/", "* /"))
        lines.append(
            "%s = %s;"
            % (
                strings_literal(key),
                strings_literal(render_flat(parse_icu(entry.value), entry)),
            )
        )
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


# --------------------------------------------------------------------------
# Swift lane: Localizable.stringsdict
# --------------------------------------------------------------------------


def emit_stringsdict(source: Catalog, catalog: Catalog, plural_keys: Sequence[str]) -> str:
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" '
        '"http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
        "<!-- %s" % BANNER_LINE,
        "     %s -->" % BANNER_HINT,
        '<plist version="1.0">',
        "<dict>",
    ]
    for key in sorted(plural_keys):
        source_entry = source.entries[key]
        entry = Entry(
            key=key,
            value=catalog.entries[key].value,
            comment=source_entry.comment,
            placeholders=source_entry.placeholders,
        )
        nodes = parse_icu(entry.value)
        names = plural_arguments(parse_icu(source_entry.value))
        lines.append("\t<key>%s</key>" % xml_text(key))
        lines.append("\t<dict>")
        lines.append("\t\t<key>NSStringLocalizedFormatKey</key>")

        locale_plurals = plural_arguments(nodes)
        if locale_plurals:
            lines.append("\t\t<string>%s</string>" % xml_text(render_format_key(nodes, entry)))
            branch_source = {
                node[1]: node[2] for node in nodes if node[0] == PLURAL
            }
        else:
            # The translation renders the key without a plural (Simplified
            # Chinese has only `other`, and a translator may write it flat).
            # Wrap it in a single-branch variable so the key still resolves
            # through the same .stringsdict lookup in every locale.
            name = names[0]
            positional = uses_positional(entry)
            if positional:
                index = entry.placeholder_order.index(name) + 1
                lines.append("\t\t<string>%%%d$#@%s@</string>" % (index, name))
            else:
                lines.append("\t\t<string>%%#@%s@</string>" % name)
            branch_source = {name: [("other", nodes)]}

        for name in names:
            branches = branch_source.get(name)
            if branches is None:
                raise CatalogError(
                    "%s: %s is missing the plural for {%s}" % (rel(catalog.path), key, name)
                )
            kind = entry.placeholders[name]
            lines.append("\t\t<key>%s</key>" % xml_text(name))
            lines.append("\t\t<dict>")
            lines.append("\t\t\t<key>NSStringFormatSpecTypeKey</key>")
            lines.append("\t\t\t<string>NSStringPluralRuleType</string>")
            lines.append("\t\t\t<key>NSStringFormatValueTypeKey</key>")
            lines.append("\t\t\t<string>%s</string>" % FORMAT_SPECIFIER[kind])
            for selector, body in sorted(branches, key=lambda pair: selector_sort_key(pair[0])):
                lines.append("\t\t\t<key>%s</key>" % xml_text(selector))
                lines.append(
                    "\t\t\t<string>%s</string>"
                    % xml_text(render_flat(body, entry, plural_name=name))
                )
            lines.append("\t\t</dict>")
        lines.append("\t</dict>")

    lines.append("</dict>")
    lines.append("</plist>")
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------
# Swift lane: the typed API
# --------------------------------------------------------------------------


class _Namespace(object):
    def __init__(self, name: str):
        self.name = name
        self.children: Dict[str, "_Namespace"] = {}
        self.members: List[Tuple[str, str]] = []  # (member identifier, catalog key)


def _build_tree(keys: Sequence[str]) -> _Namespace:
    root = _Namespace("L10n")
    for key in sorted(keys):
        segments = key.split(".")
        node = root
        for segment in segments[:-1]:
            name = swift_namespace(segment)
            if name not in node.children:
                node.children[name] = _Namespace(name)
            node = node.children[name]
        node.members.append((swift_identifier(segments[-1]), key))
    return root


def emit_l10n_swift(source: Catalog, catalogs: Sequence[Catalog]) -> str:
    plural_keys = sorted(
        key for key, entry in source.entries.items() if plural_arguments(parse_icu(entry.value))
    )
    plural_set = set(plural_keys)
    locales = sorted(catalog.locale for catalog in catalogs)

    lines = [
        "// %s" % BANNER_LINE,
        "// %s" % BANNER_HINT,
        "//",
        "import Foundation",
        "",
        "/// Every user-facing string in Vibe Bar, resolved through the",
        "/// bundle that ``L10n/bundle`` picks.",
        "///",
        "/// Members are computed, not stored: ``L10n/localeOverride`` can change",
        "/// at any point in a session, and a `static let` would cache the string",
        "/// it resolved the first time anybody touched it.",
    ]
    root = _build_tree(list(source.entries.keys()))
    lines += _emit_namespace(root, source, plural_set, indent="", is_root=True)
    lines.append("")
    lines += _emit_facts(source, locales, plural_keys)
    return "\n".join(lines).rstrip("\n") + "\n"


def _emit_namespace(
    node: _Namespace,
    source: Catalog,
    plural_set: "set",
    indent: str,
    is_root: bool = False,
) -> List[str]:
    keyword = "public enum %s {" % node.name
    lines = [indent + keyword]
    inner = indent + "    "

    for member, key in node.members:
        entry = source.entries[key]
        lines += _emit_member(entry, member, plural_set, inner)
        lines.append("")

    for name in sorted(node.children):
        lines += _emit_namespace(node.children[name], source, plural_set, inner)
        lines.append("")

    while lines and lines[-1] == "":
        lines.pop()
    lines.append(indent + "}")
    return lines


def _emit_member(entry: Entry, member: str, plural_set: "set", indent: str) -> List[str]:
    lines: List[str] = []
    if entry.comment:
        lines += doc_comment(entry.comment, indent)
        lines.append(indent + "///")
    lines += doc_comment("Key: `%s`" % entry.key, indent)
    lines += doc_comment('en: "%s"' % entry.value.replace("\\", "\\\\"), indent)

    order = entry.placeholder_order
    if not order:
        lines.append(
            "%spublic static var %s: String { L10nSupport.string(%s) }"
            % (indent, member, swift_literal(entry.key))
        )
        return lines

    signature = ", ".join(
        "%s: %s" % (swift_identifier(name), SWIFT_TYPE[entry.placeholders[name]])
        for name in order
    )
    arguments = ", ".join(swift_identifier(name) for name in order)
    call = "localizedFormat" if entry.key in plural_set else "format"
    lines.append(
        "%spublic static func %s(%s) -> String {" % (indent, member, signature)
    )
    lines.append(
        "%s    L10nSupport.%s(%s, %s)"
        % (indent, call, swift_literal(entry.key), arguments)
    )
    lines.append(indent + "}")
    return lines


def _emit_facts(source: Catalog, locales: Sequence[str], plural_keys: Sequence[str]) -> List[str]:
    lines = [
        "/// Catalog facts the tests and any future tooling need, so neither has",
        "/// to re-read `catalog/*.json` at runtime (AGENTS.md § 2, rule 7).",
        "enum L10nCatalogFacts {",
        "    static let sourceLocale = %s" % swift_literal(SOURCE_LOCALE),
        "",
        "    static let locales: [String] = [",
    ]
    for locale in locales:
        lines.append("        %s," % swift_literal(locale))
    lines += ["    ]", "", "    static let keys: [String] = ["]
    for key in sorted(source.entries):
        lines.append("        %s," % swift_literal(key))
    lines += ["    ]", "", "    static let pluralKeys: Set<String> = ["]
    for key in plural_keys:
        lines.append("        %s," % swift_literal(key))
    lines += ["    ]", "", "    static let placeholderCounts: [String: Int] = ["]
    for key in sorted(source.entries):
        lines.append(
            "        %s: %d," % (swift_literal(key), len(source.entries[key].placeholders))
        )
    lines += ["    ]", "}"]
    return lines


# --------------------------------------------------------------------------
# TypeScript lane
# --------------------------------------------------------------------------


def ts_param_type(entry: Entry) -> str:
    if not entry.placeholders:
        return "undefined"
    fields = "; ".join(
        "%s: %s" % (ts_string(name), TS_TYPE[entry.placeholders[name]])
        for name in entry.placeholder_order
    )
    return "{ %s }" % fields


def emit_ts_catalog(source: Catalog, catalogs: Sequence[Catalog]) -> str:
    ordered = sorted(catalogs, key=lambda catalog: catalog.locale)
    keys = sorted(source.entries)
    lines = [
        "// %s" % BANNER_LINE,
        "// %s" % BANNER_HINT,
        "",
        "/** The locale a string is authored in; every other locale falls back to it. */",
        "export const sourceLocale = %s;" % ts_string(SOURCE_LOCALE),
        "",
        "/** Every locale the catalog ships. */",
        "export const locales = [",
    ]
    for catalog in ordered:
        lines.append("  %s," % ts_string(catalog.locale))
    lines += [
        "] as const;",
        "",
        "export type Locale = (typeof locales)[number];",
        "",
        "/** Every key in the catalog. A typo is a compile error, not a blank label. */",
        "export type MessageKey =",
    ]
    for index, key in enumerate(keys):
        suffix = ";" if index == len(keys) - 1 else ""
        lines.append("  | %s%s" % (ts_string(key), suffix))
    lines += [
        "",
        "/**",
        " * The parameter object each key takes. `undefined` means the key takes",
        " * no second argument at all — `t` overloads on this.",
        " */",
        "export interface MessageParams {",
    ]
    for key in keys:
        lines.append("  %s: %s;" % (ts_string(key), ts_param_type(source.entries[key])))
    lines += [
        "}",
        "",
        "/** Raw ICU messages, per locale. Formatted by `t` — never read directly. */",
        "export const messages: {",
        "  readonly [L in Locale]: { readonly [K in MessageKey]: string };",
        "} = {",
    ]
    for catalog in ordered:
        lines.append("  %s: {" % ts_string(catalog.locale))
        for key in keys:
            lines.append(
                "    %s: %s," % (ts_string(key), ts_string(catalog.entries[key].value))
            )
        lines.append("  },")
    lines += ["};", ""]
    return "\n".join(lines).rstrip("\n") + "\n"


# --------------------------------------------------------------------------
# Driving
# --------------------------------------------------------------------------


def build_outputs(catalogs: Sequence[Catalog]) -> "Dict[str, str]":
    """Relative path -> file content. Nothing is written here."""
    by_locale = {catalog.locale: catalog for catalog in catalogs}
    if SOURCE_LOCALE not in by_locale:
        raise CatalogError("catalog/%s.json is missing; it is the source locale" % SOURCE_LOCALE)
    source = by_locale[SOURCE_LOCALE]

    plural_keys = sorted(
        key for key, entry in source.entries.items() if plural_arguments(parse_icu(entry.value))
    )

    outputs: Dict[str, str] = {}
    for catalog in sorted(catalogs, key=lambda item: item.locale):
        lproj = "implementations/swift/Resources/%s.lproj" % catalog.locale
        outputs["%s/Localizable.strings" % lproj] = emit_strings(source, catalog, plural_keys)
        if plural_keys:
            outputs["%s/Localizable.stringsdict" % lproj] = emit_stringsdict(
                source, catalog, plural_keys
            )

    outputs["implementations/swift/Sources/VibeBarLocalization/Generated/L10n.swift"] = (
        emit_l10n_swift(source, catalogs)
    )
    outputs["implementations/typescript/src/generated/catalog.ts"] = emit_ts_catalog(
        source, catalogs
    )
    return outputs


def write_outputs(out_root: str, outputs: "Dict[str, str]") -> List[str]:
    written: List[str] = []
    for relative in sorted(outputs):
        target = os.path.join(out_root, relative)
        directory = os.path.dirname(target)
        if not os.path.isdir(directory):
            os.makedirs(directory)
        with open(target, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(outputs[relative])
        written.append(relative)
    return written


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--out", default=None, help="write into this directory instead")
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if a checked-in file differs",
    )
    parser.add_argument("--quiet", action="store_true", help="print nothing on success")
    args = parser.parse_args(list(argv) if argv is not None else None)

    from _catalog import REPO_ROOT

    try:
        outputs = build_outputs(load_all())
    except CatalogError as exc:
        sys.stderr.write("generate: %s\n" % exc)
        return 1

    root = args.out or REPO_ROOT
    if args.check:
        stale = [
            relative
            for relative in sorted(outputs)
            if _read(os.path.join(root, relative)) != outputs[relative]
        ]
        for relative in stale:
            sys.stderr.write("generate: %s is stale; run python3 scripts/generate.py\n" % relative)
        return 1 if stale else 0

    written = write_outputs(root, outputs)
    if not args.quiet:
        for relative in written:
            print("wrote %s" % relative)
    return 0


def _read(path: str) -> Optional[str]:
    try:
        with open(path, "r", encoding="utf-8") as handle:
            return handle.read()
    except OSError:
        return None


if __name__ == "__main__":
    sys.exit(main())
